// Arcade (CPS-3, 990512) versions of routines in Source/Game/active06.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active06.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0606B24A
//   PS2 case 2: Normal_Attack arg2 0x110 -> 0x90
void Pattern06_0007(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x44, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FFC, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B2D6
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Pattern06_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x44, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FFC, 6, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B412
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Pattern06_0012(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x80, 2);
        break;

    case 1:
        Command_Attack(wk, 8, 0x20, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B550
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Pattern06_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B570
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern06_0020(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B590
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Pattern06_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B5CC
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Pattern06_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B5EC
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern06_0023(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B60C
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern06_0024(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B8CA
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern06_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FA8, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B91E
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern06_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F88, -0x7FC0, 9, 0x200, 0, -0x7F88, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B960
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern06_0039(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F68, -0x7FC0, 9, 0x100, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B9A2
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern06_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F68, -0x7FC0, 9, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606BDBE
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern06_0056(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 8, 0x42, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606BE0C
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
void Pattern06_0057(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 9, 0x42, 0, -0x7F68, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 3:
        Wait(wk, 0xA);
        break;

    case 4:
        Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
