// Arcade (CPS-3, 990512) versions of routines in Source/Game/active13.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active13.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x06074E58
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Pattern13_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06074ECE
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Pattern13_0007(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06074EEE
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Pattern13_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06074F5C
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern13_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06074FA8
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern13_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_On(wk, 1, 2);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075000
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern13_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060751B4
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern13_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC0, 8, 0x200, 0, -0x7F90, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060753C0
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Adjust_Attack arg2 0x400 -> 0x200
void Pattern13_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 0xC, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 0xC, 0x80);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075508
//   PS2 case 1: Normal_Attack arg2 0x110 -> 0x90
void Pattern13_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075640
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern13_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_On(wk, 1, 0);
        break;

    case 1:
        Adjust_Attack(wk, 0xB, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 0xA, 0x102);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607569C
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern13_0039(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075740
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern13_0041(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075780
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Pattern13_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_On(wk, 1, 2);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060757D0
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
void Pattern13_0043(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC0, 8, 0x200, 0, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075874
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
void Pattern13_0045(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FC0, 8, 0x200, 0, -1, -1, 0xFFFFFFFF);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075AB4
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Pattern13_0055(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075AF8
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern13_0056(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Search_Back_Term(wk, 0x60, 2, 0x10);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, -0x7FB8, 8, 0x200, 1, -0x7F90, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075EEA
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern13_0069(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 8, 0x40, 0, -0x7F90, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075F50
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
void Pattern13_0070(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06075F94
//   PS2 case 0: Lever_Attack arg3 0x400 -> 0x200
void Pattern13_0072(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
