// Arcade (CPS-3, 990512) versions of routines in Source/Game/active05.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active05.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0606A150
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
void Pattern05_0001(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A190
//   PS2 case 0: Command_Attack arg3 9 -> 8
void Pattern05_0002(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x41D, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A24A
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern05_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A2D6
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Pattern05_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 0, 0x100, 0, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A376
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern05_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A396
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern05_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A3D6
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern05_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A3F6
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern05_0014(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC8, 8, 0x100, 2, -0x7F80, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A504
//   PS2 case 1: Lever_Attack arg3 0x400 -> 0x200
void Pattern05_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, 0x88, -1, 0, 2, 5);
        break;

    case 1:
        Lever_Attack(wk, 8, 1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A5D8
//   PS2 case 0: Jump_Attack_Term arg8 0x100 -> 0x80
void Pattern05_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 8, 0x40, 0, -0x7F90, -1, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A72A
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
void Pattern05_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x41D, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A794
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
void Pattern05_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A7D4
//   PS2 case 0: Jump_Attack_Term arg4 0x202 -> 0x102
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern05_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F50, -0x7FB0, 8, 0x102, 0, -0x7F68, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A8C0
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Pattern05_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0, 0x80);
        break;

    case 1:
        Lever_Off(wk);
        break;

    case 2:
        Look(wk, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A934
//   PS2 case 0: Lever_Attack arg3 0x400 -> 0x200
void Pattern05_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606A956
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 4: Lever_Attack arg3 0x400 -> 0x200
void Pattern05_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SA_Term(wk, 0x35, 0xFFFFFFFF, 0x37, 0);
        break;

    case 1:
        Pierce_On(wk);
        break;

    case 2:
        Adjust_Attack(wk, 0xB, 0x20);
        break;

    case 3:
        Normal_Attack(wk, 0xA, 0x102);
        break;

    case 4:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606AA26
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern05_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606AACC
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Pattern05_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606AB50
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern05_0044(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 8, 0x40, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606AC5C
//   PS2 case 0: Hi_Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern05_0047(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Command_Attack_Term(wk, 8, 0x1F, 0xA, -1, -0x7FA0, 0x30, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606ACCA
//   PS2 case 0: Hi_Jump_Attack arg3 0x400 -> 0x200
void Pattern05_0050(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack(wk, 8, 0xA, 0x200, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606AFB4
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern05_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 8, 0x100, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B014
//   PS2 case 0: Jump_Attack_Term arg4 0x402 -> 0x202
void Pattern05_0064(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x50, 8, 0x202, 2, -0x7F80, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606B056
//   PS2 case 0: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern05_0065(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x50, 8, 0x102, 2, -0x7F80, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
