// Arcade (CPS-3, 990512) versions of routines in Source/Game/active18.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active18.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0608102C
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0002(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FA8, 1, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081076
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern18_0003(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060811B2
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern18_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608122E
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern18_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608124E
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern18_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608138E
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0018(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FA8, 1, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060813D8
//   PS2 case 0: Normal_Attack -> Lever_Attack
void Pattern18_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081464
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern18_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060814A6
//   PS2 case 0: Jump_Attack arg3 0x400 -> 0x200
void Pattern18_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack(wk, 8, 0xF, 0x200, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060815E2
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x200 -> 0x100
//   PS2 case 2: Adjust_Attack arg2 0x400 -> 0x200
void Pattern18_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x100);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081650
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x402 -> 0x202
void Pattern18_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608167C
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern18_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081778
//   PS2 case 0: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Adjust_Attack arg2 0x200 -> 0x100
void Pattern18_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060817F6
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Pattern18_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081948
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Pattern18_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081EC0
//   PS2 case 0: Jump_Command_Attack_Term arg4 0x700 -> 0x380
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0061(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, 0x380, -1, -0x7FA8, 1, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081F24
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern18_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081F46
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern18_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06081F68
//   PS2 case 0: Normal_Attack arg2 0x110 -> 0x90
void Pattern18_0064(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06082248
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Pattern18_0078(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06082268
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Pattern18_0079(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060822C2
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0081(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 8, -1, -1, -0x7FA8, 2, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608230C
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FA8, 2, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06082374
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0083(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -1, -0x7FA8, 2, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060823F8
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0085(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 8, -1, -1, -0x7FA8, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06082442
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0086(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FA8, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060824A4
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0087(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -1, -0x7FA8, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06082528
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0089(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 8, -1, -1, -0x7FA8, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06082572
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0090(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FA8, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060825D4
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern18_0091(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -1, -0x7FA8, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608261E
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Pattern18_0092(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608265E
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern18_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x100);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060827BE
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Pattern18_0098(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060828D0
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Pattern18_0102(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
