// Arcade (CPS-3, 990512) versions of routines in Source/Game/active07.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active07.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0606C064
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Pattern07_0001(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C130
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Pattern07_0003(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x200);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C1C6
//   PS2 case 1: Lever_Attack arg3 0x400 -> 0x200
void Pattern07_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x40);
        break;

    case 1:
        Lever_Attack(wk, 0xB, 0, 0x200);
        break;

    case 2:
        Command_Attack(wk, 8, 1, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C29A
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Lever_Attack arg3 0x200 -> 0x100
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Pattern07_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 8, 0x40, 0, -0x7F90, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C380
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Lever_Attack arg3 0x200 -> 0x100
void Pattern07_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 8, 0x40, 0, -0x7F90, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C3E0
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
//   PS2 case 1: Lever_Attack arg3 0x202 -> 0x102
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Pattern07_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    case 1:
        Lever_Attack(wk, 0xB, 0, 0x102);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C448
//   PS2 case 0: Lever_Attack arg3 0x400 -> 0x200
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern07_0012(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C476
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern07_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 1:
        J_Command_Attack(wk, 9, 0x1E, 9, -1);
        break;

    case 2:
        Search_Back_Term(wk, 0x60, 1, -1);
        break;

    case 3:
        Command_Attack(wk, 8, 1, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C4DC
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
void Pattern07_0014(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 8, 0x100, 2, -0x7F80, -1, 0x100);
        break;

    case 1:
        Lever_Attack(wk, 9, 0, 0x100);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C62E
//   PS2 case 0: Jump_Attack_Term arg4 0x100 -> 0x80
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
void Pattern07_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F9C, -0x7FC0, 8, 0x80, 0, -0x7F90, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x20, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C70E
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Pattern07_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F9C, -0x7FC0, 8, 0x20, 0, -0x7F90, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x200);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1C, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C7AA
//   PS2 case 0: Jump_Attack_Term arg8 0x100 -> 0x80
void Pattern07_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 8, 0x40, 0, -0x7F90, -1, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C98E
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
void Pattern07_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606C9F4
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Lever_Attack arg3 0x200 -> 0x100
void Pattern07_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CA26
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern07_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x100, 0, -0x7F68, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CA78
//   PS2 case 2: Lever_Attack arg3 0x100 -> 0x80
void Pattern07_0032(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 2:
        Lever_Attack(wk, 0xB, 0, 0x80);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CB3A
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 2: Normal_Attack arg2 0x200 -> 0x100
void Pattern07_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 3:
        Lever_Off(wk);
        break;

    case 4:
        Look(wk, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CBFC
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern07_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    case 1:
        Search_Back_Term(wk, 0x60, 1, -1);
        break;

    case 2:
        Command_Attack(wk, 8, 1, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CC4E
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 4: Lever_Attack arg3 0x400 -> 0x200
void Pattern07_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 1:
        Pierce_On(wk);
        break;

    case 2:
        Adjust_Attack(wk, 0xB, 0x20);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 4:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CD28
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern07_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CD68
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Pattern07_0041(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x20, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CDCC
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern07_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CE62
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern07_0044(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 8, 0x40, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CEA6
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
void Pattern07_0045(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 8, 0x200, 0, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CF1E
//   PS2 case 0: Hi_Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern07_0047(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Command_Attack_Term(wk, 8, 0x2E, 9, -1, -0x7FA0, 0x38, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CF66
//   PS2 case 1: Lever_Attack arg3 0x100 -> 0x80
void Pattern07_0048(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x20);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x80);
        break;

    case 2:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 0xA, -1, -1, 0x38, 1, -1, -1, 0xFFFFFFFF);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606CFF8
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Lever_Attack arg3 0x100 -> 0x80
//   PS2 case 2: Lever_Attack arg3 0x100 -> 0x80
//   PS2 case 3: Normal_Attack arg2 0x200 -> 0x100
void Pattern07_0049(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FC8, 8, 0x100, 0, -0x7FA8, -1, 0x100);
        break;

    case 1:
        Lever_Attack(wk, 9, 0, 0x80);
        break;

    case 2:
        Lever_Attack(wk, 9, 0, 0x80);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606D062
//   PS2 case 0: Hi_Jump_Attack arg3 0x400 -> 0x200
void Pattern07_0050(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack(wk, 8, 0xA, 0x200, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606D094
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern07_0051(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FC8, 8, 0x20, 0, -0x7FA8, -1, 0x100);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606D2CC
//   PS2 case 2: Normal_Attack arg2 0x200 -> 0x100
//   PS2 case 3: Normal_Attack arg2 0x400 -> 0x200
void Pattern07_0059(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0, 0xB, -1);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 9, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x100);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
