// Arcade (CPS-3, 990512) versions of routines in Source/Game/active14.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active14.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0607623E
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Pattern14_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076280
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern14_0006(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060762A0
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Pattern14_0007(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076320
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Pattern14_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076340
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0012(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076374
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern14_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076632
//   PS2 case 2: Jump_Command_Attack_Term arg10 0x400 -> 0x200
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0026(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 2:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, -1, -1, 0x30, 0, -0x7F80, -1, 0x200);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 4:
        J_Command_Attack(wk, 0xB, 0x20, 8, -1);
        break;

    case 5:
        Wait(wk, 5);
        break;

    case 6:
        SA_Term(wk, 0x2F, 0xFFFFFFFF, 0x31, 0x7F);
        break;

    case 7:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607674C
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern14_0028(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, -1, -1, 0x30, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060767B8
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 0xB, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607685C
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 0xB, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    case 4:
        Wait(wk, 1);
        break;

    case 5:
        SA_Term(wk, 0x2F, 0x30, 0x31, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060768F4
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 0xB, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076998
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0032(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 0xB, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    case 4:
        Wait(wk, 1);
        break;

    case 5:
        SA_Term(wk, 0x2F, 0x30, 0x31, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076A60
//   PS2 case 2: Jump_Command_Attack_Term arg10 0x400 -> 0x200
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 2:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, -1, -1, 0x30, 0, -0x7F80, -1, 0x200);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 4:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 5:
        Wait(wk, 3);
        break;

    case 6:
        J_Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076BAA
//   PS2 case 1: Hi_Jump_Attack_Term arg4 0x202 -> 0x102
//   PS2 case 1: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0035(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Hi_Jump_Attack_Term(wk, -1, 0x61, 8, 0x102, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076C20
//   PS2 case 1: Hi_Jump_Attack_Term arg4 0x202 -> 0x102
//   PS2 case 1: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0036(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Hi_Jump_Attack_Term(wk, -1, 0x61, 8, 0x102, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    case 4:
        Wait(wk, 1);
        break;

    case 5:
        SA_Term(wk, 0x2F, 0x30, 0x31, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076CE2
//   PS2 case 1: Hi_Jump_Attack_Term arg4 0x202 -> 0x102
//   PS2 case 1: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Hi_Jump_Attack_Term(wk, -1, 0x61, 8, 0x102, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        Pierce_On(wk);
        break;

    case 4:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 5:
        Wait(wk, 3);
        break;

    case 6:
        J_Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076ED2
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        ETC_Term(wk, 3, 2, 0);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    case 3:
        Wait(wk, 1);
        break;

    case 4:
        SA_Term(wk, 0x2F, 0x30, 0x31, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06076F56
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0043(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        ETC_Term(wk, 3, 2, 0);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077444
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0058(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 9, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 3:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 4:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060774C4
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0059(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 9, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 3:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 4:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    case 5:
        Wait(wk, 1);
        break;

    case 6:
        SA_Term(wk, 0x2F, 0x30, 0x31, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077590
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x220 -> 0x120
void Pattern14_0060(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 9, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 3:
        SA_Term(wk, 0x32, 0xFFFFFFFF, 0xFFFFFFFF, 0xBF);
        break;

    case 4:
        Com_Random_Select(wk, 6, 0x77, 0x77, 0x78, 0x79, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077658
//   PS2 case 2: Hi_Jump_Attack_Term arg4 0x202 -> 0x102
//   PS2 case 2: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0061(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Hi_Jump_Attack_Term(wk, -1, 0x61, 9, 0x102, 0, -0x7F80, -1, 0x200);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 4:
        SA_Term(wk, 0x32, 0xFFFFFFFF, 0xFFFFFFFF, 0xBF);
        break;

    case 5:
        Com_Random_Select(wk, 6, 0x77, 0x77, 0x78, 0x79, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060776F4
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x220 -> 0x120
void Pattern14_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC8, 9, 0x200, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 3:
        SA_Term(wk, 0x34, 0x34, 0x34, 0x7F);
        break;

    case 4:
        Com_Random_Select(wk, 6, 0x77, 0x77, 0x78, 0x79, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060777B2
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 3: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 4: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, -1, -1, 0x34, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 4:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 5:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    case 6:
        Wait(wk, 1);
        break;

    case 7:
        SA_Term(wk, 0x2F, 0x30, 0x31, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060778A8
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 4: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 5: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0064(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, -1, -1, 0x34, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Lever_Attack(wk, 9, 0, 0x20);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 4:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 5:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 6:
        Command_Attack(wk, 0xC, 0x1F, 0xA, -1);
        break;

    case 7:
        Wait(wk, 1);
        break;

    case 8:
        SA_Term(wk, 0x2F, 0x30, 0x31, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060779AE
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
void Pattern14_0065(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, -1, -1, 0x34, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 4:
        SA_Term(wk, 0x32, 0xFFFFFFFF, 0xFFFFFFFF, 0xBF);
        break;

    case 5:
        Com_Random_Select(wk, 6, 0x77, 0x77, 0x78, 0x79, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077A50
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern14_0066(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, -1, -1, 0x34, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        SA_Term(wk, 0x34, 0x34, 0x34, 0x7F);
        break;

    case 3:
        Com_Random_Select(wk, 6, 0x77, 0x77, 0x78, 0x79, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077DAC
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0076(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 2:
        SA_Term(wk, 0x34, 0x34, 0x34, 0x7F);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077E24
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0077(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077E68
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 2: Normal_Attack arg2 0x200 -> 0x100
void Pattern14_0078(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077ED8
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0079(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077F3A
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Pattern14_0080(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077F66
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0081(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077FC4
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Pattern14_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xD, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06077FF0
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 5: Normal_Attack arg2 0x400 -> 0x200
void Pattern14_0083(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 4:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 5:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078078
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 6: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 7: Normal_Attack arg2 0x400 -> 0x200
void Pattern14_0084(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 4:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 5:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 6:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 7:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078106
//   PS2 case 0: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0085(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607816E
//   PS2 case 1: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0086(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060781BC
//   PS2 case 0: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 7: Normal_Attack arg2 0x402 -> 0x202
void Pattern14_0087(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x120);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 4:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 5:
        Lever_On(wk, 1, 2);
        break;

    case 6:
        Wait(wk, 2);
        break;

    case 7:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078268
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Lever_Attack arg3 0x110 -> 0x90
void Pattern14_0088(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        SA_Term(wk, 0x34, 0x34, 0x34, 0x7F);
        break;

    case 2:
        Approach_Walk(wk, 0x10, 2);
        break;

    case 3:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060782C6
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 3: Lever_Attack arg3 0x110 -> 0x90
void Pattern14_0089(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        SA_Term(wk, 0x34, 0x34, 0x34, 0x7F);
        break;

    case 2:
        Approach_Walk(wk, 0x10, 2);
        break;

    case 3:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607834C
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 5: Lever_Attack arg3 0x110 -> 0x90
void Pattern14_0090(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        SA_Term(wk, 0x34, 0x34, 0x34, 0x7F);
        break;

    case 4:
        Approach_Walk(wk, 0x10, 2);
        break;

    case 5:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060783CE
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 7: Lever_Attack arg3 0x110 -> 0x90
void Pattern14_0091(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 4:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 5:
        SA_Term(wk, 0x34, 0x34, 0x34, 0x7F);
        break;

    case 6:
        Approach_Walk(wk, 0x10, 2);
        break;

    case 7:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078496
//   PS2 case 1: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0092(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x4C, 0x4D, 0x4E, 0x4F, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078500
//   PS2 case 1: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x50, 0x51, 0x52, 0x53, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078598
//   PS2 case 1: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0094(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x54, 0x55, 0x56, 0x57, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078602
//   PS2 case 1: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0095(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x58, 0x59, 0x5A, 0x5B, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060787C8
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern14_0100(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -0x7F60, 0x50, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x4C, 0x4D, 0x4E, 0x4F, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607884E
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern14_0101(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -0x7F60, 0x50, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x50, 0x51, 0x52, 0x53, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060788C4
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern14_0102(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -0x7F60, 0x50, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x54, 0x55, 0x56, 0x57, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607895C
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern14_0103(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 3);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -0x7F60, 0x50, 0, -0x7F80, -1, 0x200);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x58, 0x59, 0x5A, 0x5B, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078ADA
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0108(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 1, -1, -1);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x4C, 0x4D, 0x4E, 0x4F, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078B7E
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0109(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 1, -1, -1);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x50, 0x51, 0x52, 0x53, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078C02
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0110(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 1, -1, -1);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x54, 0x55, 0x56, 0x57, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06078CA4
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0111(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 1, -1, -1);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x58, 0x59, 0x5A, 0x5B, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060794D0
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0132(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x78, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060794FC
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern14_0133(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x86, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079528
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern14_0134(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x77, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079554
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Pattern14_0135(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x84, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060795E0
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0137(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 2:
        Pierce_On(wk);
        break;

    case 3:
        J_Command_Attack(wk, 0xB, 0x20, 8, -1);
        break;

    case 4:
        Wait(wk, 5);
        break;

    case 5:
        SA_Term(wk, 0x2F, 0xFFFFFFFF, 0x31, 0x7F);
        break;

    case 6:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079668
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0138(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 1:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 2:
        Pierce_On(wk);
        break;

    case 3:
        J_Command_Attack(wk, 0xB, 0x20, 8, -1);
        break;

    case 4:
        Wait(wk, 5);
        break;

    case 5:
        SA_Term(wk, 0x2F, 0xFFFFFFFF, 0x31, 0x7F);
        break;

    case 6:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079712
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern14_0139(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 2:
        Pierce_On(wk);
        break;

    case 3:
        J_Command_Attack(wk, 0xB, 0x20, 9, -1);
        break;

    case 4:
        Wait(wk, 3);
        break;

    case 5:
        J_Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060797A8
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern14_0140(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 2:
        Pierce_On(wk);
        break;

    case 3:
        J_Command_Attack(wk, 0xB, 0x20, 9, -1);
        break;

    case 4:
        Wait(wk, 3);
        break;

    case 5:
        J_Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079854
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0142(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x57, 3);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x89, 0x8A, 0x8B, 0x8C, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060798FA
//   PS2 case 1: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0143(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 2:
        Com_Random_Select(wk, 2, 0x89, 0x8A, 0x8B, 0x8C, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060799C0
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0145(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x57, 3);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x4C, 0x4D, 0x4E, 0x4F, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079A38
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0146(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x57, 3);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x50, 0x51, 0x52, 0x53, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079AD0
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0147(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x57, 3);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x54, 0x55, 0x56, 0x57, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06079B48
//   PS2 case 2: Jump_Attack_Term arg4 0x202 -> 0x102
void Pattern14_0148(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x57, 3);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, 0x49, 9, 0x102, 0, -0x7F80, -1, 0x40);
        break;

    case 3:
        Com_Random_Select(wk, 2, 0x58, 0x59, 0x5A, 0x5B, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
