// Arcade (CPS-3, 990512) versions of routines in Source/Game/active08.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active08.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0606D810
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0001(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606D84E
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Pattern08_0002(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606D932
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DA10
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 8, 0x100, 0, -0x7F98, -1, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DB0E
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DB2E
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern08_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        J_Command_Attack(wk, 9, 0x1E, 0xA, -1);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DBC4
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Pattern08_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DC0A
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x100 -> 0x80
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0014(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC8, 8, 0x100, 2, -1, -0x7FF0, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DD5E
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
void Pattern08_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, 0x70, -1, 0, 2, 5);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DE4A
//   PS2 case 0: Jump_Attack_Term arg8 0x100 -> 0x80
void Pattern08_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F98, -0x7FC0, 9, 0x40, 0, -0x7F90, -1, 0x80);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606DFD0
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Lever_Attack arg3 0x402 -> 0x202
void Pattern08_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x40);
        break;

    case 3:
        Lever_Attack(wk, 8, 0, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E02E
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x200 -> 0x100
void Pattern08_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E088
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F98, -0x7FC0, 8, 0x100, 0, -0x7F68, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E12A
//   PS2 case 1: Lever_Attack arg3 0x402 -> 0x202
void Pattern08_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 9, 0, 0x20);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E15A
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x40);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x202);
        break;

    case 3:
        Pierce_On(wk);
        break;

    case 4:
        Command_Attack(wk, 8, 1, 0xA, -1);
        break;

    case 5:
        Lever_Off(wk);
        break;

    case 6:
        Look(wk, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E240
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern08_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E262
//   PS2 case 2: Adjust_Attack arg2 0x200 -> 0x100
//   PS2 case 4: Lever_Attack arg3 0x402 -> 0x202
void Pattern08_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SA_Term(wk, 0x39, 0x3A, 0xFFFFFFFF, 0);
        break;

    case 1:
        Pierce_On(wk);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x100);
        break;

    case 3:
        Lever_Attack(wk, 8, 0, 0x20);
        break;

    case 4:
        Lever_Attack(wk, 8, 0, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E33C
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern08_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1C, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E37C
//   PS2 case 2: Lever_Attack arg3 0x402 -> 0x202
void Pattern08_0041(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x40);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E3E8
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Pattern08_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 8, 0x100, 0, -0x7F70, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E42C
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern08_0043(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F98, -0x7FC0, 8, 0x40, 0, -1, -0x7FE0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E470
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0044(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F98, -0x7FC0, 8, 0x40, 0, -0x7F70, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E4C2
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Pattern08_0045(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F98, -0x7FC0, 0xB, 0x200, 0, -0x7F70, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606E664
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
void Pattern08_0050(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F98, -0x7FB8, 8, 0x200, 2, -1, -0x7FF0, 0x10);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606EAFC
//   PS2 case 0: Command_Attack arg4 0x700 -> 0x380
void Pattern08_0068(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 9, 0x1F, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606EB80
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x100 -> 0x80
void Pattern08_0070(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F98, -0x7FC0, 9, 0x200, 0, -0x7F90, -1, 0x80);
        break;

    case 1:
        Command_Attack(wk, 9, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
