// Arcade (CPS-3, 990512) versions of routines in Source/Game/active16.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active16.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0607E824
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern16_0003(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E960
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern16_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E9DE
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern16_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E9FE
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern16_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EA3E
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
void Pattern16_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EB3C
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern16_0018(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 9, -1, -0x7FA0, 0x40, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EB84
//   PS2 case 0: Lever_Attack arg3 0x400 -> 0x200
void Pattern16_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EC10
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern16_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607ED8A
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x200 -> 0x100
//   PS2 case 2: Lever_Attack arg3 0x400 -> 0x200
void Pattern16_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 0xC, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x100);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EDF0
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
void Pattern16_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x42);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EE1C
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern16_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x100, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EF12
//   PS2 case 0: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Adjust_Attack arg2 0x200 -> 0x100
void Pattern16_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607EFF0
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern16_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 0xB, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xA, 0x102);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607F080
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern16_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607F652
//   PS2 case 0: Command_Attack arg4 0x700 -> 0x380
void Pattern16_0059(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x1D, 9, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607F6D4
//   PS2 case 0: Jump_Command_Attack_Term arg4 0x700 -> 0x380
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Pattern16_0061(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 9, 0x380, -0x7FA0, 0x40, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607F71E
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern16_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607F740
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern16_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607F826
//   PS2 case 0: Normal_Attack arg2 0x110 -> 0x90
void Pattern16_0067(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
