// Arcade (CPS-3, 990512) versions of routines in Source/Game/active01.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active01.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x06065838
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern01_0003(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065972
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern01_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060659EE
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern01_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065A0E
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern01_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065B7A
//   PS2 case 0: Lever_Attack arg3 0x400 -> 0x200
void Pattern01_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065C0C
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern01_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065D86
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x200 -> 0x100
//   PS2 case 2: Adjust_Attack arg2 0x400 -> 0x200
void Pattern01_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x100);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065DF4
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x402 -> 0x202
void Pattern01_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065E20
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern01_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065F14
//   PS2 case 0: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Adjust_Attack arg2 0x200 -> 0x100
void Pattern01_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06065FD4
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern01_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 0xB, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xA, 0x102);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06066074
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern01_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06066110
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Pattern01_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060665FE
//   PS2 case 0: Command_Attack arg4 0x700 -> 0x380
void Pattern01_0059(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x20, 9, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06066680
//   PS2 case 0: Command_Attack arg4 0x700 -> 0x380
void Pattern01_0061(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x1F, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060666B2
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern01_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060666D4
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern01_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060667FC
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern01_0069(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC8, 0xC, 0x40, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
