// Arcade (CPS-3, 990512) versions of routines in Source/Game/active15.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/active15.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0607D7A6
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern15_0003(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607D8E0
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Pattern15_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607D95E
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Pattern15_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607D97E
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern15_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DACC
//   PS2 case 0: Jump_Attack arg3 0x202 -> 0x102
void Pattern15_0018(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack(wk, 8, 0xC, 0x102, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DAFE
//   PS2 case 0: Lever_Attack arg3 0x400 -> 0x200
void Pattern15_0019(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DB40
//   PS2 case 1: Jump_Attack arg3 0x202 -> 0x102
void Pattern15_0020(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    case 1:
        Jump_Attack(wk, 8, 0xC, 0x102, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DB88
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Pattern15_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DD10
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x200 -> 0x100
//   PS2 case 2: Adjust_Attack arg2 0x400 -> 0x200
void Pattern15_0029(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x100);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DD82
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Adjust_Attack arg2 0x402 -> 0x202
void Pattern15_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 9, 0x80);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DDAE
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Pattern15_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x100, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DE42
//   PS2 case 0: Adjust_Attack arg2 0x100 -> 0x80
void Pattern15_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x80);
        break;

    case 1:
        Branch_Unit_Area(wk, 2, 1, 0x31, 0x32, 0x33);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DEAA
//   PS2 case 0: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Adjust_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Adjust_Attack arg2 0x200 -> 0x100
void Pattern15_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 1:
        Adjust_Attack(wk, 8, 0x82);
        break;

    case 2:
        Adjust_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607DF84
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Pattern15_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Adjust_Attack(wk, 0xB, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xA, 0x102);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E006
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Pattern15_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E0A2
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Pattern15_0042(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x12);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x22);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E4D0
//   PS2 case 0: Command_Attack arg4 0x700 -> 0x380
void Pattern15_0056(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x1C, 9, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E5E2
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Pattern15_0061(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 2, 2);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1F, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E622
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern15_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E644
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Pattern15_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E6B0
//   PS2 case 0: Rapid_Command_Attack arg3 0x100 -> 0x80
void Pattern15_0065(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Rapid_Command_Attack(wk, 8, 0x4D, 0x80, 0x78);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E6E2
//   PS2 case 0: Rapid_Command_Attack arg3 0x400 -> 0x200
void Pattern15_0066(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Rapid_Command_Attack(wk, 8, 0x4D, 0x200, 0x78);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E714
//   PS2 case 0: Normal_Attack_SP arg2 0x200 -> 0x100
void Pattern15_0067(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack_SP(wk, 8, 0x100, 0x12);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0607E736
//   PS2 case 0: Rapid_Command_Attack arg3 0x100 -> 0x80
void Pattern15_0068(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Rapid_Command_Attack(wk, 8, 0x4D, 0x80, 0x78);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
