// Arcade (CPS-3, 990512) versions of routines in Source/Game/PASS02.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/PASS02.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0601D4C0
//   PS2 case 0: J_Command_Attack arg4 0x700 -> 0x380
void Passive02_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        J_Command_Attack(wk, 8, 0x1E, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601D6B6
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive02_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FD0, 8, 0x100, 0, -0x7F70, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601D7EC
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive02_0016(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x37, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601D850
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0017(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x7F, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601D99E
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive02_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 8, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DB78
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0027(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DBB8
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Passive02_0028(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DC10
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive02_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DC52
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive02_0032(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DC90
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive02_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DCD2
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive02_0035(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DD10
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive02_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FF8, 0, 1, -1);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DD7C
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive02_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FF8, 0, 1, -1);
        break;

    case 1:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DE10
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive02_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF0, 0, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601DF68
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive02_0044(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x37, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF8, 3, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E034
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive02_0047(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E074
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive02_0048(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E108
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive02_0050(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7FB0, -1, 5, 6, 0x1F);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E170
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0052(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E248
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive02_0056(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x40, 8, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E28A
//   PS2 case 0: Jump_Attack_Term arg4 0x100 -> 0x80
void Passive02_0057(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC8, 8, 0x80, 0, -0x7F78, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E3A2
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive02_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1F, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E4BE
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive02_0065(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x37, 2);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E63C
//   PS2 case 6: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0070(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x40, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Wait(wk, 0xA);
        break;

    case 3:
        SA_Term(wk, 0x35, 0x36, 0xFFFFFFFF, 0x47);
        break;

    case 4:
        SA_Term(wk, 0xFFFFFFFF, 0xFFFFFFFF, 0x19, 0x3C);
        break;

    case 5:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 6:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E7CA
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0073(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SA_Term(wk, 0x35, 0xFFFFFFFF, 0x37, 0);
        break;

    case 1:
        Adjust_Attack(wk, 0xB, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 0xA, 0x102);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1F, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E962
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive02_0077(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Attack_Complete(wk, 3, 1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601E9BA
//   PS2 case 4: Command_Attack arg4 0x700 -> 0x380
void Passive02_0078(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Check_EX(wk, 6, 0x70);
        break;

    case 3:
        Pierce_On(wk);
        break;

    case 4:
        Command_Attack(wk, 8, 0x1F, 8, 0x380);
        break;

    case 5:
        Check_BOSS_EX(wk, 1, 0xFFFFFFFF);
        break;

    case 6:
        EM_Term(wk, -0x7F58, -1, 0, 1, -1);
        break;

    case 7:
        Wait(wk, 2);
        break;

    case 8:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601EAD4
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive02_0080(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x42);
        break;

    case 2:
        Command_Attack(wk, 0xC, 0x1C, 0xA, -1);
        break;

    case 3:
        Wait(wk, 5);
        break;

    case 4:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601EB5E
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive02_0081(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x40, 0, -0x7FB0, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x40);
        break;

    case 2:
        Command_Attack(wk, 0xC, 0x1D, 0xA, -1);
        break;

    case 3:
        Wait(wk, 5);
        break;

    case 4:
        SA_Term(wk, 0x35, 0x36, 0xFFFFFFFF, 0x47);
        break;

    case 5:
        SA_Term(wk, 0xFFFFFFFF, 0xFFFFFFFF, 0x19, 0x3C);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601EC26
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x10, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF0, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 3:
        Command_Attack(wk, 0xC, 0x1D, 0xA, -1);
        break;

    case 4:
        Wait(wk, 5);
        break;

    case 5:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601ED10
//   PS2 case 0: Jump_Attack_Term arg4 0x100 -> 0x80
void Passive02_0084(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC0, 9, 0x80, 1, -0x7FB0, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601ED52
//   PS2 case 0: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0085(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x120);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1D, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601EDDA
//   PS2 case 0: Jump_Command_Attack_Term arg4 0x700 -> 0x380
//   PS2 case 0: Jump_Command_Attack_Term arg8 0x700 -> 0x380
void Passive02_0087(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2E, 8, 0x380, -0x7FA0, 0x48, 0, 0x380, 0x30, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601EE54
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0088(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 4:
        Command_Attack(wk, 8, 0x1D, 0xA, -1);
        break;

    case 5:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601F070
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive02_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x40, 0, -0x7FB0, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 2:
        Command_Attack(wk, 0xC, 0x1D, 0xA, -1);
        break;

    case 3:
        Wait(wk, 5);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601F260
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive02_0100(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FA0, 0, 2, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601F310
//   PS2 case 1: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive02_0102(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, 0x30, 0, 1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FD0, 8, 0x100, 0, -0x7F70, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601F5F4
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive02_0111(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F88, -0x7FD0, 0, 2, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601F7D6
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive02_0116(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601F994
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
void Passive02_0121(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 0xB, 0x200, 0, -0x7FB0, -1, 0x20);
        break;

    case 1:
        EM_Term(wk, -1, -0x8000, 4, 1, -1);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0x7F);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601FA7C
//   PS2 case 1: J_Command_Attack arg4 0x700 -> 0x380
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive02_0123(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1E, 0xA, 0x380);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601FB90
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive02_0127(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F90, -0x7FC0, 9, 0x40, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x40);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601FC2C
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Passive02_0128(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601FD34
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Passive02_0132(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 8, 0, -1, -1);
        break;

    case 2:
        EM_Term(wk, -1, -0x7FD0, 6, 1, -1);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
