// Arcade (CPS-3, 990512) versions of routines in Source/Game/PASS05.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/PASS05.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0602535E
//   PS2 case 1: J_Command_Attack arg3 9 -> 8
void Passive05_0007(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F88, -1, 0, 1, -1);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x41D, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602553C
//   PS2 case 1: Lever_Attack arg3 0x400 -> 0x200
void Passive05_0012(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F90, 0, 0, 2, 0);
        break;

    case 1:
        Lever_Attack(wk, 8, 1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025632
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive05_0016(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3F, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602566C
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive05_0017(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x67, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060257A2
//   PS2 case 1: Jump_Attack_Term arg4 0x402 -> 0x202
void Passive05_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, 0x40, 8, 0x202, 0, -0x7F68, -1, 0x10);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025866
//   PS2 case 2: Lever_Attack arg3 0x400 -> 0x200
void Passive05_0024(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xB7, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025960
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive05_0027(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025A34
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive05_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025A76
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive05_0032(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025A98
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive05_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025ADA
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive05_0035(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025B3C
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive05_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FF8, 0, 1, -1);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025B82
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive05_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FF8, 0, 1, -1);
        break;

    case 1:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025D50
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive05_0044(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3F, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF8, 3, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025DA4
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive05_0045(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025DE4
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive05_0047(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1E, 8, 0x70);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025E24
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Passive05_0048(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025E92
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive05_0050(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025ED6
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive05_0052(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06025FC0
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Passive05_0056(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FC0, 0, 1, -1);
        break;

    case 1:
        Command_Attack(wk, 8, 0x20, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602600C
//   PS2 case 0: Jump_Attack_Term arg4 0x402 -> 0x202
void Passive05_0057(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x40, 8, 0x202, 2, -0x7F80, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026130
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive05_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026210
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive05_0065(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x67, 2);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026348
//   PS2 case 4: Normal_Attack arg2 0x202 -> 0x102
void Passive05_0070(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x67, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0x60);
        break;

    case 3:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060264AC
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 4: Normal_Attack arg2 0x200 -> 0x100
void Passive05_0073(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F80, -1, 5, 1, -1);
        break;

    case 1:
        SA_Term(wk, 0x35, 0xFFFFFFFF, 0x37, 0);
        break;

    case 2:
        Adjust_Attack(wk, 0xB, 0x10);
        break;

    case 3:
        Normal_Attack(wk, 0xA, 0x102);
        break;

    case 4:
        Normal_Attack(wk, 0xA, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026656
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive05_0077(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Attack_Complete(wk, 3, 1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060266B0
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive05_0078(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3F, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602670E
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive05_0081(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FA8, 9, 0x40, 0, -0x7FB0, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x40);
        break;

    case 3:
        Command_Attack(wk, 9, 0x1E, 0xA, -1);
        break;

    case 4:
        SA_Term(wk, 0x35, 0x36, 0x37, 0x60);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060267C0
//   PS2 case 2: Normal_Attack arg2 0x200 -> 0x100
void Passive05_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3F, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF0, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x100);
        break;

    case 3:
        Command_Attack(wk, 9, 0x1C, 0xA, -1);
        break;

    case 4:
        SA_Term(wk, 0x35, 0x36, 0x37, 0x60);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026862
//   PS2 case 0: Jump_Attack_Term arg4 0x202 -> 0x102
void Passive05_0084(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC0, 9, 0x102, 1, -0x7FB0, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060268D8
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
void Passive05_0085(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7FA0, -0x7FF8, 5, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 0xD, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026A12
//   PS2 case 0: Normal_Attack arg2 0x220 -> 0x120
void Passive05_0089(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x120);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026AD2
//   PS2 case 0: Jump_Attack_Term arg4 0x202 -> 0x102
void Passive05_0092(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x50, 8, 0x102, 2, -0x7F80, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026B36
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
void Passive05_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7F78, 9, 0x200, 0, -0x7FA0, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
