// Arcade (CPS-3, 990512) versions of routines in Source/Game/pass00.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/pass00.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x060171C6
//   PS2 case 3: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 3, -1);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017246
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0014(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017286
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive00_0016(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x71, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 3, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601741E
//   PS2 case 4: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Check_BOSS(wk, 6, 0x17);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, -0x7FC0, 0xB, 0x40, 0, -0x7F90, -1, 0x20);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060174BE
//   PS2 case 3: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0023(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, -0x7FC0, 0xB, 0x10, 0, -1, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x10);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601752A
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0024(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017648
//   PS2 case 0: Normal_Attack arg2 0x220 -> 0x120
void Passive00_0028(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x120);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017730
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0032(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601775C
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive00_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601778A
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060177D4
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive00_0035(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601781A
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive00_0036(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FE8, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 3:
        ETC_Term(wk, 0, 6, 0x99);
        break;

    case 4:
        Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017894
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive00_0037(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FFE, 6, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601790C
//   PS2 case 1: Normal_Attack arg2 0x110 -> 0x90
void Passive00_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FFE, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017A2A
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
void Passive00_0041(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FF0, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017AE8
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0043(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_BOSS(wk, 6, 0x1B);
        break;

    case 1:
        EM_Term(wk, -0x7F80, -0x7FB0, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017C2E
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive00_0047(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017D12
//   PS2 case 0: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive00_0051(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x120);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017D58
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive00_0052(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017E16
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x100 -> 0x80
void Passive00_0056(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA8, 8, 0x80, 0, -1, -1, 0xFFFFFFFF);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017EBA
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0059(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        ETC_Term(wk, 0, 6, 0x34);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017F70
//   PS2 cases 3 -> 2
void Passive00_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06017FE4
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive00_0065(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018162
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive00_0070(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018190
//   PS2 case 1: Normal_Attack arg2 0x220 -> 0x120
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Passive00_0071(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x120);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x12);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060181E6
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0072(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 0xC, 0, 0xB, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018258
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
void Passive00_0073(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 8, 0x200, 0, -0x7F90, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x42);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060182B2
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0074(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018360
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
void Passive00_0076(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xB1, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, -0x7FC0, 8, 0x200, 0, -0x7F90, -1, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x10);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x42);
        break;

    case 4:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060183E4
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0077(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC0, 0xB, 0x40, 0, -0x7F90, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601845C
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 3: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0078(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC0, 0xB, 0x200, 0, -0x7F90, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601851A
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0080(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FB0, 0xB, 0x40, 0, -0x7F90, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018592
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0081(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7F90, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060185EC
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x40, 0, -1, -1, 0xFFFFFFFF);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018660
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
void Passive00_0083(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7F90, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x42);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060186D4
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x200 -> 0x100
void Passive00_0084(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7F90, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060188D2
//   PS2 case 2: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 2: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive00_0088(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Approach_Walk(wk, 0xB1, 2);
        break;

    case 2:
        Jump_Attack_Term(wk, -1, -0x7FC0, 0xB, 0x200, 0, -0x7F90, -1, 0x100);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x42);
        break;

    case 4:
        J_Command_Attack(wk, 0xB, 0x1F, 0xA, -1);
        break;

    case 5:
        ETC_Term(wk, 2, 6, 1);
        break;

    case 6:
        Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018ABE
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive00_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018B90
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive00_0096(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FF0, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018BD4
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive00_0097(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FFE, 6, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018C28
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
void Passive00_0098(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x33, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF0, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x42);
        break;

    case 4:
        Check_BOSS(wk, 6, 0xE);
        break;

    case 5:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06018FBE
//   PS2 case 3: Lever_Attack arg3 0x200 -> 0x100
void Passive00_0109(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        EM_Term(wk, -1, -0x7F90, 6, 1, -1);
        break;

    case 2:
        J_Command_Attack(wk, 0xB, 0x1F, 0xA, -1);
        break;

    case 3:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060192A8
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive00_0116(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x10, 8, 0x200, 1, -1, 0x10, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019312
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive00_0117(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x10, 8, 0x100, 1, -1, 0x10, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019396
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive00_0119(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x10, 8, 0x200, 0, -1, 0x10, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060193D8
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive00_0120(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x10, 8, 0x100, 0, -1, 0x10, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019516
//   PS2 case 4: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0124(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        EM_Term(wk, -1, 0x30, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x42);
        break;

    case 3:
        Wait(wk, 5);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019596
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0125(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Search_Back_Term(wk, 0x48, 6, 0x22);
        break;

    case 1:
        Walk(wk, 1, 0x18, 0);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019746
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0131(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x71, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601984A
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
void Passive00_0136(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0601994C
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0141(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F70, -0x7FC0, 8, 0x40, 2, -1, -0x7FB0, 0x40);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060199CC
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive00_0142(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F70, -0x7FC0, 9, 0x40, 2, -1, -1, -1);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019B04
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive00_0146(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F70, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019B90
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive00_0148(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FC0, 0xB, 0x200, 1, -0x7F90, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019BF8
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Passive00_0149(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019C5C
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0151(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F90, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06019CA0
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive00_0152(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x47, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
