// Arcade (CPS-3, 990512) versions of routines in Source/Game/PASS07.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/PASS07.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x06029E9E
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0004(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7FA0, 0x28, 7, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029F42
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0006(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF8, 6, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029FA4
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0007(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FF8, 6, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A032
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FC0, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A108
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Lever_Attack arg3 0x200 -> 0x100
void Passive07_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FD0, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 4:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    case 5:
        Command_Attack(wk, 8, 0x20, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A192
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FB8, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A272
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive07_0014(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A29E
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0015(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A2D6
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
void Passive07_0016(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x78, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A324
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0017(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A3C2
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive07_0020(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A3F0
//   PS2 case 1: Lever_Attack arg3 0x400 -> 0x200
void Passive07_0021(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A440
//   PS2 case 1: Lever_Attack arg3 0x202 -> 0x102
void Passive07_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A4AE
//   PS2 case 2: Lever_Attack arg3 0x100 -> 0x80
void Passive07_0024(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x20);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x80);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A678
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive07_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Lever_Attack(wk, 8, 0x1E, 0xA);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A6D0
//   PS2 case 2: Lever_Attack arg3 0x400 -> 0x200
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0031(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x10);
        break;

    case 2:
        Lever_Attack(wk, 9, 0, 0x200);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A716
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
//   PS2 case 2: Lever_Attack arg3 0x402 -> 0x202
void Passive07_0032(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Lever_Attack(wk, 0xB, 0, 0x100);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602A752
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
void Passive07_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602AA10
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive07_0043(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, 0x40, 8, 0x100, 0, -0x7FC0, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602AA52
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive07_0044(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 8, 0x200, 0, -0x7FC0, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602AC1C
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive07_0051(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602AC7E
//   PS2 case 1: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: J_Command_Attack arg4 0x700 -> 0x380
void Passive07_0052(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 2);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x20, 0, -0x7FB0, -1, 0x100);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1E, 9, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602ACE6
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0053(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x200);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1C, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602AD78
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0054(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 3, -1);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602ADB0
//   PS2 case 2: Lever_Attack arg3 0x200 -> 0x100
void Passive07_0055(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 1:
        Wait(wk, 4);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602AED8
//   PS2 case 1: Lever_Attack arg3 0x110 -> 0x90
void Passive07_0058(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602AFF0
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 3, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B01C
//   PS2 case 2: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 2: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 5: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 2:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x100);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 5:
        Normal_Attack(wk, 8, 0x202);
        break;

    case 6:
        Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B0E0
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0064(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B10C
//   PS2 case 1: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive07_0065(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -0x7FB0, -1, 0x200);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B220
//   PS2 case 0: Command_Attack arg4 0x700 -> 0x380
void Passive07_0068(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x20, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B272
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive07_0070(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 0xB, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B318
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive07_0072(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 1:
        Provoke(wk, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B362
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0074(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7FC0, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B3DE
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive07_0075(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7FB0, -1, 0, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B43C
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0076(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B468
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0077(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B54A
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0080(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B5B2
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive07_0081(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -0x7FB0, -1, 0x40);
        break;

    case 1:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B64C
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x20, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 4:
        Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    case 5:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B71C
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive07_0083(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B73E
//   PS2 case 0: Normal_Attack arg2 0x110 -> 0x90
void Passive07_0084(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B75E
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive07_0085(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B862
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0090(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 3:
        Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B8C6
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0091(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B94E
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
void Passive07_0092(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        Lever_Attack(wk, 0xC, 0, 0x100);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    case 4:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602B9CA
//   PS2 case 1: Lever_Attack arg3 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F80, 0x28, 7, 1, -1);
        break;

    case 1:
        Lever_Attack(wk, 9, 0, 0x100);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BA98
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0095(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1C, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BAD8
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0096(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BB84
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0098(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BBA4
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0099(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BC3C
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0101(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x102);
        break;

    case 1:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1C, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BC92
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive07_0102(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -1, -1, -1);
        break;

    case 1:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1C, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BD00
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0103(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BD60
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0104(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x202);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602BE14
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive07_0106(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C05A
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive07_0113(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    case 1:
        Search_Back_Term(wk, 0x60, 1, -1);
        break;

    case 2:
        Command_Attack(wk, 0xC, 1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C0D4
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0114(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C130
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive07_0115(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -0x7FB0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x40);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C1DA
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0117(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C21A
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0118(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C25A
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
void Passive07_0119(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C27C
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive07_0120(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C2E2
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive07_0121(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C302
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0122(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C32E
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0123(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C374
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0124(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C3D6
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0125(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 1:
        SA_Term(wk, 0x35, 0xFFFFFFFF, 0x37, 0);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C424
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0126(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C49C
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 4: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0127(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x12);
        break;

    case 3:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C520
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive07_0128(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -1, -1, -1);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1C, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C5C2
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0129(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x20, 0, -0x7FB0, -1, 0x100);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 5:
        Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C64E
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 1: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive07_0130(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -0x7FB0, -1, 0x40);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C738
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0132(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -0x7FB0, -1, 0x40);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x200);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C7C4
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0133(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -0x7FB0, -1, 0x40);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x200);
        break;

    case 2:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C842
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive07_0134(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x20, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x40);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1E, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C922
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0136(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x3B, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FC0, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C974
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0137(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x80);
        break;

    case 2:
        Command_Attack(wk, 8, 0x20, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602C9F0
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0138(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x20);
        break;

    case 4:
        J_Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602CDF6
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 4: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0147(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 8, 0, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 4:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 5:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602CE9A
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0148(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 8, 0, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602CEEE
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 4: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0149(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 8, 0, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 9, 0x102);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602CF72
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0150(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 8, 0, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602CFC6
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 5: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0151(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 8, 0, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 4:
        SA_Term(wk, 0x35, 0x36, 0xFFFFFFFF, 0);
        break;

    case 5:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D064
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0152(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x200);
        break;

    case 2:
        Command_Attack(wk, 8, 0x20, 8, -1);
        break;

    case 3:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D2C4
//   PS2 case 2: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 5: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0158(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 8, 0, -1, -1);
        break;

    case 2:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -1, -1, -1);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x12);
        break;

    case 4:
        SA_Term(wk, 0x35, 0x36, 0xFFFFFFFF, 0);
        break;

    case 5:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D3EC
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0160(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x102);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D454
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive07_0161(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 0xB, 0x100, 0, -0x7FB0, -1, 0x40);
        break;

    case 1:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D4EC
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
//   PS2 case 4: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 4: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 5: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0162(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x20, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 4:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 5:
        Normal_Attack(wk, 9, 0x202);
        break;

    case 6:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    case 7:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D5E6
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0163(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 4:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D66E
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0164(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D6EA
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0165(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x202);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D752
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0166(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D7C8
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0167(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x202);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    case 3:
        Search_Back_Term(wk, 0x30, 1, -1);
        break;

    case 4:
        Command_Attack(wk, 8, 1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D87C
//   PS2 case 0: Normal_Attack arg2 0x402 -> 0x202
void Passive07_0169(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602D94E
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0173(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DAB2
//   PS2 case 2: Normal_Attack arg2 0x200 -> 0x100
void Passive07_0176(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 3:
        J_Command_Attack(wk, 8, 0x1E, 0xA, -1);
        break;

    case 4:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DB44
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive07_0177(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x100);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1C, 0xA, -1);
        break;

    case 2:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DBA6
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive07_0178(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x40, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x40);
        break;

    case 2:
        J_Command_Attack(wk, 0xC, 0x20, 0xA, -1);
        break;

    case 3:
        Wait(wk, 5);
        break;

    case 4:
        SA_Term(wk, 0x35, 0x36, 0x37, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DC54
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0179(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DC82
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
void Passive07_0180(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    case 1:
        J_Command_Attack(wk, 8, 0x1E, 9, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DCC4
//   PS2 case 0: Lever_Attack arg3 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0181(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x20, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DD54
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive07_0183(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -0x7FC0, 9, 0x40, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x40);
        break;

    case 2:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602DDBC
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Passive07_0184(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FB0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    case 4:
        J_Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    case 5:
        Com_Random_Select(wk, 6, 0x2D, 0xFF, 0xFF, 0xFF, 2);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602E0DE
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive07_0194(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    case 1:
        Com_Random_Select(wk, 6, 1, 1, 0xC0, 0xC0, 4);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602E124
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive07_0195(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    case 1:
        Com_Random_Select(wk, 6, 1, 1, 0xC0, 0xC0, 4);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602E1DC
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive07_0197(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F70, 0x28, 7, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602E220
//   PS2 case 1: Lever_Attack arg3 0x402 -> 0x202
void Passive07_0198(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F70, 0x28, 7, 1, -1);
        break;

    case 1:
        Lever_Attack(wk, 8, 0, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602E3B4
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive07_0203(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xD, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602E45E
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive07_0206(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA0, -1, 8, 0x200, 1, -1, 0x20, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
