// Arcade (CPS-3, 990512) versions of routines in Source/Game/PASS06.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/PASS06.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x06026F0C
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive06_0007(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026F5A
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive06_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FD0, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026F9E
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive06_0009(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026FBE
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive06_0010(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026FDE
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive06_0011(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06026FFE
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive06_0012(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FC0, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060275D0
//   PS2 case 2: Normal_Attack arg2 0x110 -> 0x90
void Passive06_0032(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x44, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FFC, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06027646
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive06_0033(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x44, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FFC, 6, 1, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602769A
//   PS2 case 3: Normal_Attack arg2 0x100 -> 0x80
void Passive06_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x80, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7F80, 6, 1, -1);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06027734
//   PS2 case 3: Normal_Attack arg2 0x200 -> 0x100
void Passive06_0035(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x60, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7F80, 6, 1, -1);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06027970
//   PS2 case 2: Command_Attack arg4 0x700 -> 0x380
void Passive06_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x80, 2);
        break;

    case 1:
        EM_Term(wk, -1, -0x7FB0, 6, 1, -1);
        break;

    case 2:
        Command_Attack(wk, 8, 0x20, 8, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06027B9C
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive06_0045(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F60, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06027C02
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive06_0046(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F60, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06027D6A
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive06_0050(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F40, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06027DAE
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
void Passive06_0051(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F60, -1, 6, 1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, 0x38, 8, 0x200, 2, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06028172
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive06_0060(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 8, 0x100, 0, -0x7FA8, -1, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060281E2
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
void Passive06_0061(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F88, -0x7FC0, 8, 0x200, 0, -0x7F88, -1, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06028224
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F68, -0x7FC0, 8, 0x100, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06028266
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0063(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F68, -0x7FC0, 8, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060282C8
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0064(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 9, 0x100, 0, -0x7FA8, -1, 0x200);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x10);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06028462
//   PS2 case 2: Normal_Attack arg2 0x110 -> 0x90
void Passive06_0068(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x44, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602849A
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive06_0069(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x44, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06028552
//   PS2 case 4: Normal_Attack arg2 0x100 -> 0x80
void Passive06_0071(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x80, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 2:
        Wait(wk, 0xA);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x80);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060285DC
//   PS2 case 4: Normal_Attack arg2 0x200 -> 0x100
void Passive06_0072(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x80, 2);
        break;

    case 1:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 2:
        Wait(wk, 0xA);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1F, 0xA, -1);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06028974
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive06_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 3, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060289A0
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive06_0083(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 3, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060289E0
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive06_0084(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 3, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06028C50
//   PS2 case 1: Normal_Attack arg2 0x200 -> 0x100
void Passive06_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060291A2
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive06_0115(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FC0, 8, 0x100, 1, -0x7FA8, -1, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602923C
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0117(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F68, 0x40, 8, 0x40, 2, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060294D4
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive06_0125(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F60, -1, 0, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029548
//   PS2 case 1: Normal_Attack arg2 0x202 -> 0x102
void Passive06_0126(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F40, -1, 0, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060296D6
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0131(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 8, 0x42, 0, -0x7F68, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029750
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
void Passive06_0132(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 9, 0x42, 0, -0x7F68, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 3:
        Wait(wk, 9);
        break;

    case 4:
        EM_Term(wk, -0x7F90, -1, 4, 6, 0x89);
        break;

    case 5:
        Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060297E8
//   PS2 case 2: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 3: Normal_Attack arg2 0x100 -> 0x80
void Passive06_0133(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, 0);
        break;

    case 1:
        Turn_Over_On(wk);
        break;

    case 2:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 9, 0x42, 0, -0x7F68, -1, 0x200);
        break;

    case 3:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 4:
        Wait(wk, 9);
        break;

    case 5:
        Com_Random_Select(wk, 6, 0x8A, 0x16, 0x86, 0x87, 5);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0602998C
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
void Passive06_0136(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Turn_Over_On(wk);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F90, -0x7FA8, 9, 0x42, 0, -0x7F68, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x80);
        break;

    case 3:
        Wait(wk, 9);
        break;

    case 4:
        Com_Random_Select(wk, 6, 0x89, 0x86, 0x16, 0x87, 5);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029AD2
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Passive06_0139(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F88, -0x7FA8, 9, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029B2E
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive06_0140(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F88, -0x7FA8, 9, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029B80
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0141(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F88, -0x7FA8, 9, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    case 1:
        Branch_Unit_Area(wk, 6, 0x16, 0x16, 0x17, 0x18);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029C02
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0142(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F88, -0x7FA8, 9, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x42);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029C54
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0143(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F88, -0x7FA8, 9, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x40);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029CA6
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
void Passive06_0144(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F88, -0x7FA8, 9, 0x200, 0, -0x7F68, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029D16
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
void Passive06_0145(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F00, 0x38, 8, 0x200, 1, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06029D58
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive06_0146(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F00, 0x38, 8, 0x100, 1, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
