// Arcade (CPS-3, 990512) versions of routines in Source/Game/pass18.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/pass18.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x0605D7B0
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0012(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605D906
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0017(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DA9A
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive18_0022(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F80, -0x7FB0, 0xB, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DB0E
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0023(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F60, -0x7FB0, 0xB, 0x20, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DB94
//   PS2 case 4: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0024(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Search_Back_Term(wk, 0x60, 6, 0x6C);
        break;

    case 1:
        Pierce_On(wk);
        break;

    case 2:
        Keep_Away(wk, 0x89, 0);
        break;

    case 3:
        Wait_Get_Up(wk, 0, -1);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DBE4
//   PS2 case 6: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0025(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Search_Back_Term(wk, 0x60, 6, 0x6C);
        break;

    case 1:
        Pierce_On(wk);
        break;

    case 2:
        Keep_Away(wk, 0x89, 0);
        break;

    case 3:
        Wait_Get_Up(wk, 3, -1);
        break;

    case 4:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 5:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 6:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DCC4
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive18_0027(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DD04
//   PS2 case 0: Jump_Attack arg3 0x400 -> 0x200
void Passive18_0028(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack(wk, 8, 0xA, 0x200, 1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DD90
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0030(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x7F, 2);
        break;

    case 1:
        EM_Term(wk, -0x7F80, -0x7FB8, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DEB8
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0034(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x10);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FB8, 1, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605DF12
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0035(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E026
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0038(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FB8, 6, 1, -1);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, 0x40, 1, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E110
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 3: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0040(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -1, -0x7FF8, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E21A
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0043(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F80, -0x7FB8, 6, 1, -1);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, 0x40, 1, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E36C
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive18_0047(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E3AC
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive18_0048(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E450
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0050(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F80, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E494
//   PS2 case 0: Normal_Attack arg2 0x420 -> 0x220
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive18_0051(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x220);
        break;

    case 1:
        Normal_Attack(wk, 0xB, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E4C0
//   PS2 case 0: Normal_Attack arg2 0x202 -> 0x102
void Passive18_0052(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E5A2
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
void Passive18_0056(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F60, -0x7FA0, 8, 0x100, 0, -0x7FA0, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E702
//   PS2 case 2: Lever_Attack arg3 0x110 -> 0x90
void Passive18_0062(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x37, 2);
        break;

    case 1:
        ETC_Term(wk, 0, 2, 0xD);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E7AC
//   PS2 case 0: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0064(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E838
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0066(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FB8, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E8A8
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive18_0067(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x7F, 2);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E8D4
//   PS2 case 0: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive18_0068(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F60, -0x7FA0, 8, 0x100, 0, -0x7FA0, -1, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E948
//   PS2 case 1: Lever_Attack arg3 0x402 -> 0x202
void Passive18_0070(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0xBF, 2);
        break;

    case 1:
        Lever_Attack(wk, 8, 1, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605E9F4
//   PS2 case 2: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0072(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Pierce_On(wk);
        break;

    case 1:
        Command_Attack(wk, 0xC, 0, 0xB, -1);
        break;

    case 2:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FC0, 2, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605EBC2
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0077(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F60, -0x7FA0, 0xB, 0x40, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605EC28
//   PS2 case 0: Jump_Attack_Term arg4 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0078(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F60, -0x7FB0, 0xB, 0x80, 0, -0x7FA0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605EC82
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0079(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F60, -0x7FB0, 0xB, 0x20, 0, -0x7FA0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605ECD4
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0080(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F60, -0x7FA0, 0xB, 0x100, 0, -0x7FA0, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605ED48
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x100 -> 0x80
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0081(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F60, -0x7FA0, 0xB, 0x80, 0, -0x7FA0, -1, 0x200);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x10);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605EDA0
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0082(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -0x7F60, -0x7FA0, 0xB, 0x20, 0, -0x7FA0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605EE10
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 2: Normal_Attack arg2 0x100 -> 0x80
//   PS2 case 3: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0083(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x100, 0, -0x7FA0, -1, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605EE74
//   PS2 case 0: Hi_Jump_Attack arg3 0x400 -> 0x200
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 3: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0084(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack(wk, 0xC, 0x12, 0x200, 0);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605EEC8
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0085(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Wait(wk, 6);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 9, -1, -1, -0x7FB8, 2, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F10C
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0089(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x30, 8, -1, -1, -0x7FD0, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F174
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0090(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x30, 9, -1, -1, -0x7FD0, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F1BE
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0091(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x30, 0xA, -1, -1, -0x7FD0, 0, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F278
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
void Passive18_0093(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x12);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F30A
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive18_0096(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Approach_Walk(wk, 0x7F, 2);
        break;

    case 1:
        EM_Term(wk, -0x7F80, -0x7FD8, 6, 1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F48C
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 0: Hi_Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 1: Normal_Attack arg2 0x100 -> 0x80
void Passive18_0099(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x100, 0, -0x7FA0, -1, 0x100);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 2:
        Lever_Attack(wk, 8, 0, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F544
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive18_0101(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x80);
        break;

    case 1:
        SA_Term(wk, 0x2E, 0x2F, 0xFFFFFFFF, 0);
        break;

    case 2:
        Branch_Unit_Area(wk, 6, 0x68, 0x69, 0x6A, 0x6A);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F900
//   PS2 case 0: Hi_Jump_Attack_Term arg4 0x200 -> 0x100
void Passive18_0115(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Hi_Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x100, 0, -0x7FA0, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F95E
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
void Passive18_0116(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 0xB, 0x200, 0, -0x7FA0, -1, 0x20);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F9A0
//   PS2 case 0: Jump_Attack arg3 0x100 -> 0x80
void Passive18_0117(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack(wk, 8, 0xC, 0x80, 0);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605F9D2
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive18_0118(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605FA8A
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive18_0120(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x20, 8, 0x200, 1, -1, 0x20, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605FB50
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x400 -> 0x200
void Passive18_0123(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, 0x20, 8, 0x200, 2, -1, 0x20, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605FCB0
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Passive18_0128(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 0x36);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 9, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605FE12
//   PS2 case 1: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0133(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 0x84);
        break;

    case 1:
        Jump_Command_Attack_Term(wk, 8, 0x2F, 0xA, -1, -1, -0x7FB8, 1, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605FE9E
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Passive18_0135(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 1);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605FF08
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Passive18_0136(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 0x36);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0605FF94
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Passive18_0138(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 0x22);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060601CC
//   PS2 case 3: Command_Attack arg4 0x700 -> 0x380
void Passive18_0146(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Provoke(wk, 1);
        break;

    case 1:
        Pierce_On(wk);
        break;

    case 2:
        Command_Attack(wk, 0xC, 0, 0xB, -1);
        break;

    case 3:
        Command_Attack(wk, 8, 0x1C, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060250
//   PS2 case 1: Command_Attack arg4 0x700 -> 0x380
void Passive18_0147(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 0x36);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 0xA, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060602FA
//   PS2 case 1: Normal_Attack arg2 0x400 -> 0x200
void Passive18_0150(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -0x7F70, -0x7FB0, 8, 0x20, 2, -1, -0x7FB0, 0x20);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060378
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
void Passive18_0151(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0606039C
//   PS2 case 1: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x102 -> 0x82
void Passive18_0152(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F70, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x82);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x82);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060603E4
//   PS2 case 1: Normal_Attack arg2 0x402 -> 0x202
void Passive18_0153(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        EM_Term(wk, -0x7F70, -1, 6, 1, -1);
        break;

    case 1:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060604CA
//   PS2 case 2: Command_Attack arg4 0x700 -> 0x380
void Passive18_0156(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Check_EX(wk, 6, 0x9B);
        break;

    case 1:
        Wait(wk, 4);
        break;

    case 2:
        Command_Attack(wk, 8, 0x1D, 9, 0x380);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060516
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive18_0157(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 0, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060538
//   PS2 case 0: Lever_Attack arg3 0x110 -> 0x90
void Passive18_0158(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Lever_Attack(wk, 8, 1, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060580
//   PS2 case 0: Normal_Attack arg2 0x110 -> 0x90
void Passive18_0159(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 8, 0x90);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060607C8
//   PS2 case 0: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 0: Jump_Attack_Term arg8 0x200 -> 0x100
void Passive18_0166(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Attack_Term(wk, -1, -0x7FA0, 8, 0x200, 0, -0x7FA0, -1, 0x100);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060A34
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive18_0176(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060ADA
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive18_0178(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x100);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1C, 8, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060C34
//   PS2 case 0: Normal_Attack arg2 0x100 -> 0x80
void Passive18_0183(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x80);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1D, 8, 0x70);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060C88
//   PS2 case 0: Normal_Attack arg2 0x200 -> 0x100
void Passive18_0184(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 0xC, 0x100);
        break;

    case 1:
        Command_Attack(wk, 8, 0x1C, 8, 0x70);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06060D48
//   PS2 case 0: Normal_Attack arg2 0x102 -> 0x82
//   PS2 case 2: Normal_Attack arg2 0x402 -> 0x202
void Passive18_0187(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Normal_Attack(wk, 9, 0x82);
        break;

    case 1:
        Normal_Attack(wk, 9, 0x12);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x202);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06061078
//   PS2 case 0: Jump_Command_Attack_Term arg10 0x400 -> 0x200
void Passive18_0198(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x30, 0xA, -1, -1, -0x7FD0, 2, -1, 0x30, 0x200);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
