// Arcade (CPS-3, 990512) versions of routines in Source/Game/SHELL01.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/SHELL01.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x060844B8
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
void Shell01_0003(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA0, 0x30, 8, 0x200, 0, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608458C
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
void Shell01_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x30, 8, 0x200, 2, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060845E4
//   PS2 case 1: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Shell01_0006(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA0, 0x30, 8, 0x100, 0, -1, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060846D2
//   PS2 case 1: Jump_Attack_Term arg4 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Shell01_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x30, 0xB, 0x100, 0, -1, -1, -1);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
