// Arcade (CPS-3, 990512) versions of routines in Source/Game/SHELL11.c that differ from the PS2 build.
// Generated by tools/lift_patterns.py from the arcade program: every callee and argument below is
// what the arcade code passes. The PS2 value is noted where they differ.
#include "sf33rd/Source/Game/SHELL11.h"
#include "common.h"
#include "sf33rd/Source/Game/Com_Sub.h"
#include "sf33rd/Source/Game/workuser.h"

// 0x060858DC
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 3: Normal_Attack arg2 0x202 -> 0x102
void Shell11_0003(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F20, -0x7FD0, 9, 0x200, 0, -0x7FB0, -1, 0x100);
        break;

    case 2:
        Normal_Attack(wk, 0xB, 0x20);
        break;

    case 3:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x0608596C
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Shell11_0004(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F20, -0x7FD0, 0xB, 0x200, 0, -0x7FB0, -1, 0x20);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x060859D8
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
//   PS2 case 1: Jump_Attack_Term arg8 0x400 -> 0x200
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Shell11_0005(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7F20, -0x7FC0, 0xB, 0x200, 0, -0x7FB0, -1, 0x200);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06085A6E
//   PS2 case 1: Jump_Attack_Term arg4 0x400 -> 0x200
void Shell11_0006(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 1, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -1, 0x30, 8, 0x200, 2, -1, -1, -1);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06085AF8
//   PS2 case 1: Jump_Attack_Term arg8 0x200 -> 0x100
//   PS2 case 2: Normal_Attack arg2 0x202 -> 0x102
void Shell11_0008(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        SHELL_Term(wk, 0, 2, 1, -1, -1);
        break;

    case 1:
        Jump_Attack_Term(wk, -0x7FA8, -0x7FD0, 0xB, 0x20, 0, -0x7FB0, -1, 0x100);
        break;

    case 2:
        Normal_Attack(wk, 8, 0x102);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}

// 0x06085C62
//   PS2 case 0: Jump_Command_Attack_Term arg4 0x700 -> 0x380
void Shell11_0013(PLW* wk) {
    switch (CP_Index[wk->wu.id][0]) {
    case 0:
        Jump_Command_Attack_Term(wk, 8, 0x1E, 0xA, 0x380, -1, 0x30, 0, -1, -1, 0xFFFFFFFF);
        break;

    default:
        End_Pattern(wk);
        break;
    }
}
